# Generated by Django 5.1.1 on 2024-09-21 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone must be 10 digits')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='USN must be in the format: 2sd23is048', regex='^[0-9]{1}[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{3}$')]),
        ),
    ]
