# Generated by Django 5.1.1 on 2024-09-22 14:33

import CampusFlow.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0002_alter_profile_bio_alter_profile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Enter a Valid Number')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=CampusFlow.models.get_profile_image_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='USN must be in the format: 2sd23is048', regex='^[0-9]{1}[a-zA-Z]{2}[0-9]{2}[a-zA-Z]{2}[0-9]{3}$')]),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=CampusFlow.models.get_post_image_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, choices=[('OC', 'Outside Campus'), ('GT', 'Ganesh Temple'), ('KT', 'Knowledge Tree'), ('SC', 'Suruchi'), ('CF', 'Cafe'), ('FC', 'Food Court'), ('MS', 'Mess'), ('LB', 'Library')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusFlow.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusFlow.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CampusFlow.post')),
            ],
        ),
    ]
