# Generated by Django 5.1.1 on 2024-09-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0003_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('descriprion', models.TextField()),
                ('image', models.ImageField(upload_to='ads')),
                ('event_date', models.DateField()),
                ('location', models.CharField(blank=True, choices=[('SM', 'Seminar Hall'), ('MS', 'MBA Seminar Hall'), ('CF', 'Cafe'), ('FC', 'Food Court'), ('LB', 'Library')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
