# Generated by Django 5.1.1 on 2024-09-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0007_remove_profile_follower_profile_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friendship',
            new_name='rapport',
        ),
    ]
