# Generated by Django 5.1.1 on 2024-09-27 09:46

import CampusFlow.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0009_rapportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_images/default/default_image.png', upload_to=CampusFlow.models.get_profile_image_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usn',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='USN must be in the format: 2sd23XXYYY', regex='^[0-9]{1}[A-Z]{2}[0-9]{2}[A-Z]{2}[0-9]{3}$')]),
        ),
    ]
