# Generated by Django 5.1.1 on 2024-10-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0012_alter_advertisement_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rapport',
        ),
    ]
