# Generated by Django 5.1.1 on 2024-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0013_remove_profile_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
