# Generated by Django 5.1.1 on 2024-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0014_profile_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rapport',
            field=models.ManyToManyField(blank=True, to='CampusFlow.profile'),
        ),
    ]
