# Generated by Django 5.1.1 on 2024-11-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0019_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
